// One-time setup for the wa-channels scheduler.
// Run from the Hive folder:  node modules/wa-channels/setup.mjs
//
// 1. Adds WA_CRON_SECRET (and the other WA_* settings, if missing) to .env.local.
// 2. Writes modules/wa-channels/db/schedule.local.sql — paste it into the Supabase
//    SQL editor. It stores the secret in Supabase Vault and creates a pg_cron job
//    that pings /api/wa/tick every minute. (That file holds the secret: it's
//    git-ignored via *.local.* — delete it after running.)
// Prints nothing secret.

import { existsSync, readFileSync, appendFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

const ENV = ".env.local";
const OUT = "modules/wa-channels/db/schedule.local.sql";
const SITE = process.argv[2] || "https://hive-wine-rho.vercel.app";

const env = existsSync(ENV) ? readFileSync(ENV, "utf8") : "";
const has = (k) => new RegExp(`^${k}=`, "m").test(env);
const existing = env.match(/^WA_CRON_SECRET=(.+)$/m)?.[1]?.trim();
const secret = existing || randomBytes(32).toString("base64url");

const lines = [];
if (!has("WA_CHANNELS_ENABLED")) lines.push("WA_CHANNELS_ENABLED=true");
if (!has("WA_API_TOKEN")) lines.push("# Paste the token from the Whapi dashboard (Channel → API token)", "WA_API_TOKEN=");
if (!has("WA_API_BASE")) lines.push("WA_API_BASE=https://gate.whapi.cloud");
if (!has("WA_PLAN")) lines.push("WA_PLAN=sandbox");
if (!has("WA_SEND_DELAY_SECONDS")) lines.push("WA_SEND_DELAY_SECONDS=10-20");
if (!existing) lines.push(`WA_CRON_SECRET=${secret}`);
if (lines.length) {
  appendFileSync(ENV, `${env === "" || env.endsWith("\n") ? "" : "\n"}\n# WhatsApp channels module (modules/wa-channels). Add these to Vercel too.\n${lines.join("\n")}\n`);
}

const sql = `-- wa-channels scheduler (generated by modules/wa-channels/setup.mjs)
-- Paste into the Supabase SQL editor, run, then DELETE this file.

create extension if not exists pg_cron;
create extension if not exists pg_net;

-- The shared secret, kept in Supabase Vault rather than in the job text.
delete from vault.secrets where name = 'wa_cron_secret';
select vault.create_secret('${secret}', 'wa_cron_secret', 'wa-channels: authenticates the scheduler ping');

-- Every minute: ask Hive to send whatever is due.
select cron.unschedule('wa-channels-tick') where exists (select 1 from cron.job where jobname = 'wa-channels-tick');
select cron.schedule(
  'wa-channels-tick',
  '* * * * *',
  $job$
  select net.http_post(
    url := '${SITE}/api/wa/tick',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-wa-cron-secret', (select decrypted_secret from vault.decrypted_secrets where name = 'wa_cron_secret')
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 60000
  );
  $job$
);
`;
writeFileSync(OUT, sql);

console.log(lines.length ? `Added ${lines.filter((l) => !l.startsWith("#")).length} WA_* settings to .env.local.` : "WA_* settings already in .env.local.");
console.log(`Wrote ${OUT} (pings ${SITE}/api/wa/tick every minute).`);
console.log("Next: paste that file into the Supabase SQL editor and run it, then delete the file.");
console.log("Also add WA_CHANNELS_ENABLED, WA_API_TOKEN, WA_API_BASE, WA_PLAN, WA_SEND_DELAY_SECONDS and WA_CRON_SECRET to Vercel (all Secret).");
