// One-time setup: creates the VAPID key pair that signs Hive's push
// notifications and adds it to .env.local. Prints only the public key.
// Run with: npm run setup:push
import { existsSync, readFileSync, appendFileSync } from "node:fs";
import webpush from "web-push";

const file = ".env.local";
const env = existsSync(file) ? readFileSync(file, "utf8") : "";

if (/^VAPID_PRIVATE_KEY=.+/m.test(env)) {
  console.log("Push keys are already in .env.local — nothing to do.");
  process.exit(0);
}

const { publicKey, privateKey } = webpush.generateVAPIDKeys();
appendFileSync(
  file,
  `${env.endsWith("\n") || env === "" ? "" : "\n"}
# Web Push (generated by npm run setup:push). Add these to Vercel too.
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${publicKey}
VAPID_PRIVATE_KEY=${privateKey}
VAPID_SUBJECT=mailto:eugene@loggedonmedia.com
`,
);

console.log("Added push keys to .env.local.");
console.log("Public key (safe to share):", publicKey);
console.log("Add NEXT_PUBLIC_VAPID_PUBLIC_KEY (Config), VAPID_PRIVATE_KEY (Secret) and VAPID_SUBJECT to Vercel,");
console.log("then restart the dev server.");
