// One-time setup: creates the shared secret The Log uses to talk to Hive, and
// writes it into BOTH projects' .env.local. Prints nothing secret.
// Run from the Hive folder with: npm run setup:the-log
import { existsSync, readFileSync, appendFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

const HIVE_ENV = ".env.local";
const LOG_ENV = "../the-log/.env.local";
const HIVE_URL = "https://hive-wine-rho.vercel.app";

const read = (f) => (existsSync(f) ? readFileSync(f, "utf8") : "");
if (/^THE_LOG_API_KEY=.+/m.test(read(HIVE_ENV))) {
  console.log("The Log key is already in Hive's .env.local — nothing to do.");
  process.exit(0);
}
if (!existsSync(LOG_ENV)) {
  console.log(`Can't find ${LOG_ENV}. Is The Log at ../the-log next to this folder?`);
  process.exit(1);
}

const key = randomBytes(32).toString("base64url");
const nl = (f) => (read(f) === "" || read(f).endsWith("\n") ? "" : "\n");

appendFileSync(HIVE_ENV, `${nl(HIVE_ENV)}\n# The Log connection (npm run setup:the-log). Add to Vercel too (Secret).\nTHE_LOG_API_KEY=${key}\n`);
appendFileSync(
  LOG_ENV,
  `${nl(LOG_ENV)}\n# Hive connection (generated by Hive's npm run setup:the-log). Add both to The Log's Vercel too (Secret).\nHIVE_URL=${HIVE_URL}\nHIVE_API_KEY=${key}\n`,
);

console.log("Done. The same key was added to:");
console.log("  Hive     .env.local → THE_LOG_API_KEY");
console.log("  The Log  .env.local → HIVE_API_KEY (and HIVE_URL=" + HIVE_URL + ")");
console.log("Add them to each project's Vercel environment variables as Secret, then redeploy both.");
